### ISSUE TITLE
Custom Bloodhound customqueries.json in my-resources/setup

### ISSUE THREAD

**Issue by scrt-gbe** [ThePorgs/Exegol-images#158]
Dear team,

I have my own Bloodhound customqueries.json file and its integration could be eased if Exegol could integrate it natively when starting a new project.

Could you add support so that one can place a Bloodhound customqueries.json file in my-resources/setup ?

Thanks in advance

**Comment by ShutdownRepo** [comment]
That's a good idea!
Moving the topic to Exegol-images

**Comment by Dramelac** [comment]
Merged in #181, feature available in nightly image and will be release in every image tag with the next stable version.
