### ISSUE TITLE
Upgrade base to debian 12

### ISSUE THREAD

**Issue by ShutdownRepo** [ThePorgs/Exegol-images#189]

**Comment by ShutdownRepo** [comment]
This will also allow to remove the hot fixes on `hcxtools` and `hcxdumptool`
https://github.com/ThePorgs/Exegol-images/blob/4b8aa9464301674e20195876f31ccc90284d97cc/sources/install.sh#L1383-L1384
https://github.com/ThePorgs/Exegol-images/blob/4b8aa9464301674e20195876f31ccc90284d97cc/sources/install.sh#L1399-L1400

**Comment by QU35T-code** [comment]
Available on the nightly image!
