### ISSUE TITLE
[BUG] Missing colorization on CrackMapExec

### ISSUE THREAD

**Issue by QU35T-code** [ThePorgs/Exegol-images#202]
### Describe the bug

There is no color on cme output when `cme` binary is used.

### Steps To Reproduce

`cme smb …`

### Exegol Wrapper Version

```Text
Last version
```

### Exegol container information

```Text
.
```

**Comment by ShutdownRepo** [comment]
Re-opening. Quick fix was to unset the cme alias that was relying on grc to colorize output. 
This was needed before CME included the right changes in its code to allow proper colorization.
Now, we just need to create a PR on CrackMapExec with the colorization of SMB1 enabled/disabled and SMB signing True/False.
Will close this this issue once PR is created on CME's repo

**Comment by ShutdownRepo** [comment]
Tried to create a PR but I'm facing a code that isn't made for these changes. The way CME logs things on protocols (smb, ldap, etc.) doesn't allow for easy colorization using rich like they're doing on the base. I created an issue to propose that feature. Hopefully they'll implement it... 
Closing here, as there's nothing to be done now on our end...

**Comment by QU35T-code** [comment]
The CME team fixed the problem and added the colors in this PR : https://github.com/mpgn/CrackMapExec/pull/93
