### ISSUE TITLE
BloodHound v5

### ISSUE THREAD

**Issue by noraj** [ThePorgs/Exegol-images#277]
### The needs

Upgrade from BH v4 to BH v5

### Description

Currently, Exegol ships BloodHound v4 from the old repository https://github.com/BloodHoundAD/BloodHound/ while BloodHound v5 is available in the new repository https://github.com/SpecterOps/BloodHound. (Architecture and technology changes, the whole thing is available as a docker-compose now)

https://github.com/ThePorgs/Exegol-images/blob/0fa6ea0f4116434b12a72697f9459b3093a53cad/sources/install/package_ad.sh#L112-L121

https://github.com/ThePorgs/Exegol-images/blob/0fa6ea0f4116434b12a72697f9459b3093a53cad/sources/assets/zsh/aliases.d/bloodhound#L1-L3

**Comment by ShutdownRepo** [comment]
Thanks for raising this. We do have a PR that's a work in progress to update bloodhound, see #222

**Comment by ShutdownRepo** [comment]
Closing, #222 is merged 🎉 
Will be in the next nightly builds and next releases
Will need to be checked since there is no easy way to have bloodhound-ce unit tested during the pipeline, but it should be fine
