### ISSUE TITLE
Create a Wireless Image with wireless penetration testing tools

### ISSUE THREAD

**Issue by stevesec** [ThePorgs/Exegol-images#288]
### The needs

Add a ```exegol install wireless``` with only wireless penetration testing tools.

### Description

Add a ```exegol install wireless``` with only wireless penetration testing tools.

**Comment by ShutdownRepo** [comment]
I'm not sure there would be that much interest in that image and the balance of interest vs. cost would be in favor of this image not being officially offered like the others.

However, I'm not discarding this proposal 100%, if more people want that.

In the mean time, here is what we can do
1. Create a `wifi.dockerfile` (or other name) with the right packages/tools in it
2. this dockerfile will allow Exegol users to [build a local image easily with the wrapper](https://exegol.readthedocs.io/en/latest/exegol-wrapper/install.html)

If that solution suits you, the best would be for you to create a pull request adding the new dockerfile

**Comment by stevesec** [comment]
Certainly! I will get to that! Thank you!

**Comment by stevesec** [comment]
Added to dev
