### ISSUE TITLE
[BUG] `install_java11` fails because only mac binaries are in the latest release

### ISSUE THREAD

**Issue by compass-dexter** [ThePorgs/Exegol-images#291]
### Describe the bug

The latest release of adoptium/temurin11-binaries (https://github.com/adoptium/temurin11-binaries/releases/tag/jdk-11.0.22%2B7.1) only contains mac binaries. Therefore the build fails.

Instead of using https://api.github.com/repos/adoptium/temurin11-binaries/releases/latest in [package_base.sh](https://github.com/ThePorgs/Exegol-images/blob/main/sources/install/package_base.sh#L324) we should use https://api.github.com/repos/adoptium/temurin11-binaries/releases and pipe it to `sort | tail -n1`.

### Steps To Reproduce

1. Build the image and wait until `install_java11` is called.

### Exegol Wrapper Version

```Text
N/A
```

### Exegol container information

```Text
N/A
```

**Comment by QU35T-code** [comment]
Merged ! Thanks @compass-dexter
