### ISSUE TITLE
Update Sherlock 0.14.3 to 1.15.0

### ISSUE THREAD

**Issue by C3LP86** [ThePorgs/Exegol-images#371]
### The needs

The issue concerns the **"OSINT"** Docker image, particularly with the Sherlock tool, which is still at version **0.14.3**. However, the developer has recently released an update to version **0.15.0**.

URL to the GitHub repository [**HERE**](https://github.com/sherlock-project/sherlock)

### Description

It is possible to use `pipx install sherlock-project` or `apt-get install sherlock` in the development of the Dockerfile for the OSINT image (or even FULL, which is normally composed of OSINT). Regarding aliases, I don't think it’s really necessary to create one; the tool can be executed directly using the command `sherlock users1 users2 ....`

URL to their documentation [**HERE**](https://fig.io/manual/pipx/upgrade)

### Alternatives

No alternative to suggest, except that this is not the most urgent request. On the OSINT image, there are tools like Maigret and Blackbird that offer similar functionalities. (It’s up to you to decide whether it’s better to update or remove the tool, which is still excellent in itself.)

**Comment by ShutdownRepo** [comment]
Thank you for opening this issue
`Sherlock` was updated 1 month ago
The latest `osint` image was built 3 months ago
On the next `osint` build (which I hope we can provide quickly), `sherlock` should be up to date. I check the install function and it installs the latest version.
Closing here. Feel free to re-open if the issue persists on the next build.
Thank you again ✌️
