### ISSUE TITLE
Feature Request: push-line-or-edit

### ISSUE THREAD

**Issue by partopronto** [ThePorgs/Exegol-images#69]
Sometimes I write longe commands and I forget IP's, paths, passwords.

Did this ever happen to you?
![doc1](https://user-images.githubusercontent.com/182337/199692365-85acd0da-7197-486a-8fda-5ca473a51f7f.png)

I come up with this solution in every day work:
1 - save the typed line (ctrl+a: in my case)
2 - use 'rp' to populate my clipboard
3 - the original command returns
4 - just paste the clipboard (ctrl+shift+c)

![doc2](https://user-images.githubusercontent.com/182337/199692414-fa576037-d60d-4a6c-959f-8f05429fcafe.png)

So I add this to my .zshrc:
```
###### save the cmd line
bindkey "^A" push-line-or-edit

###### save to clipboard
alias rp='realpathxclip $1'
realpathxclip() {
    realpath $1 | xclip -r
    realpath $1 | xclip -r -selection clipboard
    echo "Absolute Path is in both Clipboards"
}
```

I hope you like it? I suggest not to use ctrl+a as a default as it is already taken.

**Comment by ShutdownRepo** [comment]
Oh that's smart! I like it
Indeed, the `ctrl+a` shortcut is already taken for the `arsenal` command, and fyi there's an alias called `xcopy` that does `xsel --clipboard <` under the hood. So we only thing needed would be to add a bindkey for `push-line-or-edit`.

**Comment by ShutdownRepo** [comment]
@partopronto you should be able to save the command with `ctrl+q`
and since `clipcopy` already exists, I think I can close the issue. Feel free to open it again if needed
