### ISSUE TITLE
Tool history belongs to the tool

### ISSUE THREAD

**Issue by partopronto** [ThePorgs/Exegol-images#70]
_Toolusage_ in zsh-history belongs to the tool the same way as the tool belongs to its parent category.
I would put the relevant zsh-history directly in the tool installer for every tool. Therefore if a tool get removed or added so does it's relevant history. 

Example implementation:
![1](https://user-images.githubusercontent.com/182337/200114179-55c8b505-9c95-4e92-ad81-3fef624b8785.PNG)

The result will be:
![2](https://user-images.githubusercontent.com/182337/200114188-2a44314a-d35e-402e-a197-df759bc7c785.PNG)

But one could also write a python installer which reads config files for every tool installed...

**Comment by ShutdownRepo** [comment]
Completely agree, it was indeed in the todo list, thanks for raising the topic here! We are currently working on the next release of Exegol-images which will support multi-architectures as well as an improved "my-resources" feature. Once this release is over with, we'll be able to move on to this part 👍

**Comment by ShutdownRepo** [comment]
Fixed in #77, thank your for raising this issue and bouncing off ideas
