### ISSUE TITLE
Tool install missing dependencies - image OSINT

### ISSUE THREAD

**Issue by partopronto** [ThePorgs/Exegol-images#72]
following steps are missing in function 
_install_spiderfoot_ in **install.sh**

```
cd /opt/tools/spiderfoot/
pip3 install -r requierments.txt
```
also I suggest to add to command history:
`spiderfoot -l 127.0.0.1:9889`

**Comment by ShutdownRepo** [comment]
Thank you! Don't you want to create a pull request to add those changes and be referred as contributor to the project?

**Comment by QU35T-code** [comment]
Commits f712bb1 and 55b993a add requested changes and PR #75 merge on dev branch.
