### ISSUE TITLE
Install latest nmap in nightly

### ISSUE THREAD

**Issue by psyray** [ThePorgs/Exegol-images#78]
Just to keep a memory of the way to install latest nmap in the current nightly image
```sh
echo 'deb http://deb.debian.org/debian bullseye-backports main' > /etc/apt/sources.list.d/backports.list
apt update
apt install nmap/bullseye-backports -y
```

**Comment by ShutdownRepo** [comment]
Thanks! You could create a Pull Request if you'd like
If not, we'll implement the change as soon as possible, thank you 😄

**Comment by QU35T-code** [comment]
Commit 1c33c08 makes the requested changes. PR #75 sends changes to the dev branch.
