### ISSUE TITLE
[BUG] pth-net missing required libraries (libreadline.so.6)

### ISSUE THREAD

**Issue by p0dalirius** [ThePorgs/Exegol-images#80]
### Describe the bug

We cannot use the pth-net command, because of missing libreadline.so.6 library

Fix:

```sh
wget -c http://ftp.debian.org/debian/pool/main/r/readline6/libreadline6_6.3-8+b3_amd64.deb
wget -c http://ftp.debian.org/debian/pool/main/g/glibc/multiarch-support_2.19-18+deb8u10_amd64.deb
sudo apt install ./libreadline6_6.3-8+b3_amd64.deb ./multiarch-support_2.19-18+deb8u10_amd64.deb
```

### Steps To Reproduce

Any pth-net command

### Exegol Wrapper Version

```Text
4.1.1
```

### Exegol container information

```Text
nightly - v.d3d8f764
```

**Comment by p0dalirius** [comment]
Thank you :)

**Comment by Dramelac** [comment]
> Thank you for raising the issue. This issue is probably similar to [byt3bl33d3r/pth-toolkit#5](https://github.com/byt3bl33d3r/pth-toolkit/issues/5) and [byt3bl33d3r/pth-toolkit#6](https://github.com/byt3bl33d3r/pth-toolkit/issues/6). Adding your changes. Should be fixed in the next nightly build.

Maybe we should add a test command as well ?

**Comment by ShutdownRepo** [comment]
> > Thank you for raising the issue. This issue is probably similar to [byt3bl33d3r/pth-toolkit#5](https://github.com/byt3bl33d3r/pth-toolkit/issues/5) and [byt3bl33d3r/pth-toolkit#6](https://github.com/byt3bl33d3r/pth-toolkit/issues/6). Adding your changes. Should be fixed in the next nightly build.
> 
> Maybe we should add a test command as well ?

Agreed, it's in the TODO list

**Comment by ShutdownRepo** [comment]
Closing, feel free to open the issue again if it's not fixed in the next nighty build
