### ISSUE TITLE
Pre-configured Firefox

### ISSUE THREAD

**Issue by ShutdownRepo** [ThePorgs/Exegol-images#90]
### The needs

We have Firefox installed, but as base install, nothing customized

### Description

We need to install a pre-configured Firefox, with some plugins (such as FoxyProxy, DarkReader, User-Agent switcher, Cookies editor, Wappalyzer, etc.)

### Alternatives

Could be Firefox, could be Brave, Chrome or whatever's best

**Comment by ShutdownRepo** [comment]
Picked up discussion from #14

**Comment by Dramelac** [comment]
Regarding the Burp CA: cf. https://github.com/ThePorgs/Exegol-images/pull/107#issuecomment-1447790338
